"use client";

import { useState } from "react";
import { convert, inspectQuery, inverse, MODES, type Mode, type QueryResult } from "@/lib/codec";

async function copyText(value: string) { try { await navigator.clipboard.writeText(value); return true; } catch { return false; } }

export default function Home() {
  const [input, setInput] = useState("hello world?q=café & more"); const [output, setOutput] = useState(""); const [error, setError] = useState(""); const [mode, setMode] = useState<Mode>("component-encode"); const [copied, setCopied] = useState(false); const [plusAsSpace, setPlusAsSpace] = useState(false); const [query, setQuery] = useState<QueryResult | null>(null);
  const run = () => { const result = convert(mode, input, plusAsSpace); if (result.ok) { setOutput(result.value); setError(""); } else { setOutput(""); setError(result.error); } };
  const chooseMode = (next: Mode) => { setMode(next); setOutput(""); setError(""); };
  const swap = () => { if (!output) return; setInput(output); setOutput(""); setError(""); setMode(inverse(mode)); };
  const handleCopy = async () => { if (output && await copyText(output)) { setCopied(true); window.setTimeout(() => setCopied(false), 1500); } };

  return <main className="telegram-room">
    <header className="telegram-bar"><div className="telegram-mark">B/10</div><div className="telegram-name"><strong>CODED MESSAGE DESK</strong><span>CLIENT-SIDE URL UTILITY</span></div><div className="telegram-state"><i /> NO SERVER REQUIRED</div></header>
    <section className="telegram-hero"><div><p className="telegram-kicker">BOOKCHAOWALIT / MESSAGE SERVICE</p><h1>Send it in<br /><em>the right code.</em></h1><p className="hero-copy">A small telegraph desk for the characters that URLs cannot carry as-is.</p></div><div className="red-stamp"><span>PROCESSED</span><strong>10</strong><b>LOCAL DESK</b></div></section>
    <section className="message-desk" aria-label="URL encoder and decoder"><div className="mode-strip"><span>CHOOSE THE WIRE</span><div role="group" aria-label="Encoding mode">{MODES.map(({ id, label, scope }) => <button type="button" key={id} aria-pressed={mode === id} className={mode === id ? "active" : ""} onClick={() => chooseMode(id)}><strong>{label}</strong><small>{scope} · {id.endsWith("encode") ? "encode" : "decode"}</small></button>)}</div></div><div className="desk-rule"><span>MESSAGE FORM / {mode}</span><span>UTF-8 TEXT</span></div><div className="message-grid"><label className="message-slip input-slip"><span>Input message</span><textarea aria-label="Input message" value={input} onChange={(event) => { setInput(event.target.value); setCopied(false); setQuery(null); }} spellCheck={false} /></label><div className="wire-column" aria-hidden="true"><i /><b>→</b><i /></div><label className="message-slip output-slip"><span>Output telegram</span><textarea aria-label="Output telegram" value={output} readOnly spellCheck={false} placeholder="Converted text will appear here" /></label></div>{error && <p className="error-line" role="alert"><i />{error}</p>}<div className="desk-actions"><button type="button" className="convert-button" onClick={run}>Convert message <b aria-hidden="true">↗</b></button><button type="button" className="copy-button" disabled={!output} onClick={handleCopy}>{copied ? "Copied" : "Copy output"}</button><button type="button" className="copy-button" disabled={!output} onClick={swap}>Swap &amp; reverse</button><button type="button" className="copy-button" onClick={() => setQuery(inspectQuery(input))}>Inspect query string</button>{mode.endsWith("decode") ? <label className="plus-toggle"><input type="checkbox" checked={plusAsSpace} onChange={(event) => setPlusAsSpace(event.target.checked)} /> Treat + as space (form data)</label> : null}</div><p className="sr-only" role="status">{copied ? "Output copied to the clipboard." : ""}</p>{query && (query.ok ? <table className="query-table"><caption>Query parameters ({query.rows.length}) · decoded, + as space</caption><thead><tr><th scope="col">Key</th><th scope="col">Value</th></tr></thead><tbody>{query.rows.map((row, index) => <tr key={index}><th scope="row">{row.key || <em>(empty)</em>}</th><td>{row.value || <em>(empty)</em>}</td></tr>)}</tbody></table> : <p className="error-line" role="alert"><i />{query.error}</p>)}<p className="desk-note">Component encoding is for individual query values. URI encoding keeps the structure of a full address.</p></section>
    <footer className="telegram-footer"><span>BOOKCHAOWALIT / URL ENCODER</span><span>BROWSER STATE · NO MESSAGE IS SENT</span></footer>
  </main>;
}
